steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/my-app:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/my-app:${SHORT_SHA}']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # New step using cloud-sdk image
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=us-central1-docker.pkg.dev/${_PROJECT_ID}/${_REPO_NAME}/my-app:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY  # Or NONE if you *really* don't need logs
  machineType: E2_MEDIUM      # Or E2_STANDARD_2, etc. as needed
  requestedVerifyOption: VERIFIED
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET  # This is the key line

substitutions:
  _REGION: 'us-central1'
  _SERVICE_NAME: 'my-cloud-run-service'
  _REPO_NAME: 'mihir-100938484'
  _PROJECT_ID: 'dc-assi'
