steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/293112759372/mihir-100938484/my-app:${SHORT_SHA}'  # Updated region
      - '.'

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/293112759372/mihir-100938484/my-app:${SHORT_SHA}'  # Updated region

  # Step 3: Deploy to Cloud Run (Continuous Deployment)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'my-cloud-run-service'
      - '--image=us-central1-docker.pkg.dev/293112759372/mihir-100938484/my-app:${SHORT_SHA}'  # Updated region
      - '--region=us-central1'  # Updated region
      - '--platform=managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8  # Use E2 machine type
  requestedVerifyOption: VERIFIED
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

substitutions:
  _REGION: 'us-central1'  # Updated region
  _SERVICE_NAME: 'my-cloud-run-service'
  _REPO_NAME: 'mihir-100938484'
  _PROJECT_ID: '293112759372'
